# Site settings
title: HL Granite & Marble
email: hlgranite@gmail.com
url: http://www.hlgranite.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: HL Granite & Marble
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hlgranite
  - title: facebook
    url: https://www.facebook.com/hlgranite
  - title: envelope
    url: mailto:hlgranite@gmail.com
  - title: map-marker
    url: https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=Cf6wyzhpOOK7FVDFWQAdzPX9BSmhRUBfE3ZJMDGkTqsKEYPkbA&q=HLGranite+loc:+Kedah,+Malaysia&aq=&sll=6.102237,100.383797&sspn=0.029657,0.052314&vpsrc=6&ie=UTF8&hq=HLGranite&hnear=&ll=6.093587,100.382531&spn=0.001854,0.00327&t=m&z=19&cid=5343873147049093163&iwloc=A

# Postal address (add as many lines as necessary)
address:
  - line: 600 & 601, Taman Saga 2
  - line: Jalan Alor Mengkudu 05400
  - line: Alor Setar, Malaysia
  
# Credits content
credits: 'Tel/Fax: +604-7319486<br/>Mobile: +6012-4200963, +6012-4250037<br/>Email: <a href="mailto:hlgranite@gmail.com">hlgranite@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty
