# Site settings
title: HL Granite & Marble
email: hlgranite@gmail.com
url: http://www.hlgranite.com
description: "Malaysia granite marble quartz house renovation tomb nisan buddha rehal kepok."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: HL Granite & Marble Sdn. Bhd.
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hlgranite
  - title: facebook
    url: https://www.facebook.com/hlgranite
  - title: envelope
    url: mailto:hlgranite@gmail.com
  - title: map-marker
    url: https://www.google.com/maps/place/HL+GRANITE+%26+MARBLE+SDN.+BHD./@6.093093,100.382251,17z/data=!3m1!4b1!4m2!3m1!1s0x304b44583e352b7d:0x4a2940506e9c282b

# Postal address (add as many lines as necessary)
address:
  - line: 600 & 601, Taman Saga 2
  - line: Jalan Alor Mengkudu 05400
  - line: Alor Setar, Malaysia
  
# Credits content
credits: 'Tel/Fax: +604-7319486<br/>Mobile: +6012-4200963, +6012-4250037<br/>Email: <a href="mailto:hlgranite@gmail.com">hlgranite@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty
