# Site settings
title: HL Granite & Marble
email: hlgranite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is homepage of HL Granite & Marble. We provide any kind of granite and marble solution,
  specialist in house renovation, kitchen top, flooring. Also involved in
  tomb making, Chinese traditional Fengshui, and Malay Batu Nisan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hlgranite.com" # the base hostname & protocol for your site
facebook_username: hlgranite
twitter_username: hlgranite
github_username:  hlgranite

# Build settings
markdown: kramdown
